services:
  backend:
    build:
      context: ./backend
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      FLASK_APP: run:app
    command: /bin/sh -c "while sleep 1000; do :; done"

    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

    networks:
      - frontend

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    # links:
    #   - pgadmin

    # pgadmin:
    #   image: dpage/pgadmin4:latest
    #   restart: unless-stopped
    #   volumes:
    #     - pgadmin-data:/var/lib/pgadmin
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: admin@email.com
    #     PGADMIN_DEFAULT_PASSWORD: secret
    #     PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    #     PGADMIN_LISTEN_PORT: 5500
    #   ports:
    #     - 5500:5500
    #   networks:
    #     - backend

volumes:
  postgres-data:
    # pgadmin-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
